### ISSUE TITLE
controller-jenkins	invalid plugin version 'cloudbees-bitbucket-branch-source:751.vda_24678a_f781', must follow pattern '^[0-9a-zA-Z+\\.-]+$'

### ISSUE THREAD

**Issue by mkyc** [jenkinsci/bitbucket-branch-source-plugin#556]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.303.3
OS: Linux - 5.4.172-90.336.amzn2.x86_64
---
ace-editor:1.1
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
aws-java-sdk:1.12.148-310.v5e3b_c2681d79
aws-java-sdk-cloudformation:1.12.148-310.v5e3b_c2681d79
aws-java-sdk-codebuild:1.12.148-310.v5e3b_c2681d79
aws-java-sdk-ec2:1.12.148-310.v5e3b_c2681d79
aws-java-sdk-ecr:1.12.148-310.v5e3b_c2681d79
aws-java-sdk-ecs:1.12.148-310.v5e3b_c2681d79
aws-java-sdk-elasticbeanstalk:1.12.148-310.v5e3b_c2681d79
aws-java-sdk-iam:1.12.148-310.v5e3b_c2681d79
aws-java-sdk-logs:1.12.148-310.v5e3b_c2681d79
aws-java-sdk-minimal:1.12.148-310.v5e3b_c2681d79
aws-java-sdk-ssm:1.12.148-310.v5e3b_c2681d79
aws-secrets-manager-credentials-provider:0.5.6
aws-secrets-manager-secret-source:0.0.2
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-4
bouncycastle-api:2.25
branch-api:2.7.0
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloudbees-folder:6.17
command-launcher:1.2
configuration-as-code:1.55.1
credentials:2.6.1
credentials-binding:1.27.1
display-url-api:2.3.5
durable-task:493.v195aefbb0ff2
echarts-api:5.2.2-2
font-awesome-api:5.15.4-5
git:4.10.3
git-client:3.11.0
git-server:1.10
handlebars:3.0.8
jackson2-api:2.13.1-246.va8a9f3eaf46a
javax-activation-api:1.2.0-2
javax-mail-api:1.6.2-5
jaxb:2.3.0
jdk-tool:1.0
job-dsl:1.78.3
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.53
kubernetes:1.31.3
kubernetes-client-api:5.11.2-182.v0f1cf4c5904e
kubernetes-credentials:0.9.0
kubernetes-credentials-provider:0.20
lockable-resources:2.14
mailer:408.vd726a_1130320
matrix-project:1.20
metrics:4.0.2.8.1
momentjs:1.1.1
pipeline-build-step:2.15
pipeline-graph-analysis:1.11
pipeline-input-step:446.vf27b_0b_83500e
pipeline-milestone-step:100.v60a_03cd446e1
pipeline-model-api:1.9.3
pipeline-model-definition:1.9.3
pipeline-model-extensions:1.9.3
pipeline-rest-api:2.21
pipeline-stage-step:291.vf0a8a7aeeb50
pipeline-stage-tags-metadata:1.9.3
pipeline-stage-view:2.21
plain-credentials:1.8
plugin-util-api:2.13.0
popper-api:1.16.1-2
popper2-api:2.11.2-1
scm-api:595.vd5a_df5eb_0e39
script-security:1131.v8b_b_5eda_c328e
snakeyaml-api:1.29.1
ssh-credentials:1.19
sshd:3.1.0
structs:308.v852b473a2b8c
trilead-api:1.0.13
variant:1.4
workflow-aggregator:2.6
workflow-api:1136.v7f5f1759dc16
workflow-basic-steps:2.24
workflow-cps:2648.va9433432b33c
workflow-cps-global-lib:2.21
workflow-durable-task-step:2.40
workflow-job:2.42
workflow-multibranch:706.vd43c65dec013
workflow-scm-step:2.13
workflow-step-api:622.vb_8e7c15b_c95a_
workflow-support:813.vb_d7c3d2984a_0
  ```

`cloudbees-bitbucket-branch-source:751.vda_24678a_f781` is not listed because configuration fails with it
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

I use [Kubernetes Operator](https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/deploying-jenkins/) on EKS. 

### Reproduction steps

1. [deploy operator](https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/installing-the-operator/)
2. [deploy instance](https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/deploying-jenkins/)
3. add following section to configuration: 
   ```
    spec:
      master:
        basePlugins:
          - name: kubernetes
            version: "1.31.3"
          - name: workflow-job
            version: "2.42"
          - name: workflow-aggregator
            version: "2.6"
          - name: git
            version: "4.10.3"
          - name: job-dsl
            version: "1.78.3"
          - name: configuration-as-code
            version: "1.55.1"
          - name: kubernetes-credentials-provider
            version: "0.20"
          - name: aws-secrets-manager-credentials-provider
            version: "0.5.6"
          - name: branch-api
            version: "2.7.0"
          - name: cloudbees-bitbucket-branch-source
            version: "751.vda_24678a_f781"
   ```

### Expected Results

It should reload and install plugin. 

### Actual Results

operator logs: 
```
2022-02-09T13:27:01.465Z	WARN	controller-jenkins	invalid plugin version 'cloudbees-bitbucket-branch-source:751.vda_24678a_f781', must follow pattern '^[0-9a-zA-Z+\\.-]+$'	{"cr": "master"}
```

### Anything else?

I'm not sure if consider it operator issue or plugin versioning freestyle issue but even previous version (`737.vdf9dc06105be`) was good enough.
