### ISSUE TITLE
ServerUri does not support ssh

### ISSUE THREAD

**Issue by damianszczepanik** [jenkinsci/bitbucket-branch-source-plugin#609]
### Jenkins and plugins versions report

Jenkins: 2.319.2
OS: Linux - 3.10.0-1160.66.1.el7.x86_64
scm-api:595.vd5a_df5eb_0e39
cloudbees-bitbucket-branch-source:751.vda_24678a_f781
...

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux, both

### Reproduction steps

I would like to configure bitbucket so git clone goes over ssh, not https

Currently I have

unclassified:
```
  bitbucketEndpointConfiguration:
    endpoints:
    - bitbucketServerEndpoint:
        credentialsId: "jenkins-key"
        displayName: "bitbucket.local"
        manageHooks: true
        serverUrl: "https://bitbucket.local"
        webhookImplementation: NATIVE
```

but then when Jenkinsfile ir started then following code clones repository over https, not ssh
```
    stage ("Checkout pipelines") {
        checkout scm
    }
```

According to the documentation and error message, ssh could not be used

![obraz](https://user-images.githubusercontent.com/9612911/173353254-0715febb-7477-4647-b7f9-0289039e6bd8.png)

### Expected Results

ssh is supported

### Actual Results

Error message when ssh is configured
